# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PJPresentationExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for MTShopList
pod 'PJPresentation', :path => '../../PJPresentation'
pod 'MJRefresh', '~> 3.7.5'
pod 'LookinServer', :configurations => ['Debug']

end
